'use client';
import React, { useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useAuth } from '@/components/AuthProvider';
import { Alert, Box, Button, CircularProgress, IconButton, InputAdornment, TextField, Typography } from '@mui/material';
import { ArrowForwardOutlined, EmailOutlined, LockOutlined, VisibilityOffOutlined, VisibilityOutlined } from '@mui/icons-material';

export default function LoginPage() {
  const router = useRouter(); const { login } = useAuth();
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [visible, setVisible] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!email.trim() || !password.trim()) return setError('Enter your work email and password.'); setLoading(true); setError(null); try { await login(email, password); router.push('/dashboard'); } catch (requestError: any) { setError(requestError.response?.data?.message || 'We could not sign you in. Check your credentials and try again.'); } finally { setLoading(false); } };
  return <Box className="auth-form-wrap"><Box className="auth-mobile-brand">recalix</Box><Typography className="auth-kicker">WELCOME BACK</Typography><Typography component="h2" className="auth-title">Sign in to your workspace</Typography><Typography className="auth-subtitle">Pick up where your team left off.</Typography><form onSubmit={submit} className="auth-form">{error && <Alert severity="error">{error}</Alert>}<TextField label="Work email" type="email" autoComplete="email" required value={email} onChange={(event) => { setEmail(event.target.value); setError(null); }} placeholder="you@company.com" slotProps={{ input: { startAdornment: <InputAdornment position="start"><EmailOutlined /></InputAdornment> } }} /><TextField label="Password" type={visible ? 'text' : 'password'} autoComplete="current-password" required value={password} onChange={(event) => { setPassword(event.target.value); setError(null); }} slotProps={{ input: { startAdornment: <InputAdornment position="start"><LockOutlined /></InputAdornment>, endAdornment: <InputAdornment position="end"><IconButton onClick={() => setVisible(!visible)} edge="end">{visible ? <VisibilityOffOutlined /> : <VisibilityOutlined />}</IconButton></InputAdornment> } }} /><Box sx={{ display: 'flex', justifyContent: 'flex-end', mt: -.5 }}><Typography component="span" sx={{ fontSize: 12, color: 'var(--color-text-tertiary)' }}>Use the credentials from your organization admin</Typography></Box><Button className="auth-submit" type="submit" variant="contained" fullWidth disabled={loading} endIcon={loading ? <CircularProgress color="inherit" size={18} /> : <ArrowForwardOutlined />}>{loading ? 'Signing you in…' : 'Continue to Recalix'}</Button></form><Typography className="auth-switch">New to Recalix? <Link href="/register">Create your workspace</Link></Typography><Link className="auth-back" href="/">← Back to home</Link></Box>;
}
